#numpy, matplotlib and some useful packages

#### numpy array

In [14]:
import numpy as np

data = np.array([[1,2,3],[4,5,6]])
n,d = data.shape
print(data)
print(n,d)

[[1 2 3]
 [4 5 6]]
2 3


In [15]:
import numpy as np

zero_vector = np.zeros(5)
print(zero_vector)

# useful operation for numpy array
print(1-zero_vector)

# implement inner product
print(zero_vector.T) # T stands for transpose
print((1-zero_vector).T.dot(3-zero_vector))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
15.0


In [16]:
import numpy as np

# norm
vec =  1 - np.zeros(5)
# sum of every elements, norm 1
print(np.linalg.norm(vec , ord=1))
# Euclidean distance, norm 2
print(np.linalg.norm(vec , ord=2))

5.0
2.23606797749979


##### numpy inverse matrix

In [17]:
import numpy as np

#inverse matrix
mat = np.array([[2,0],[0,2]])
print(mat)
print(np.linalg.inv(mat))

[[2 0]
 [0 2]]
[[0.5 0. ]
 [0.  0.5]]


##### numpy array sum

In [18]:
import numpy as np
#useful summation on data set

a = np.array([[1, 0, 3],
             [2, 5, 4],
             [3, 6, 7]])
print(np.sum(a))
# sum as row
print(np.sum(a,axis=0))
# sum as column
print(np.sum(a,axis=1))
# keeping the dimensions
print(np.sum(a,axis=0,keepdims=True))
print(np.sum(a,axis=1,keepdims=True))

31
[ 6 11 14]
[ 4 11 16]
[[ 6 11 14]]
[[ 4]
 [11]
 [16]]


##### numpy array boolean indexing

In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 1, 3])
# For only numpy array.
c = [5,6,7,8,9]
d = [1,2,3,4]
one = a[b==1]
# for ordinary array, the statement "d==1" is False.
# so d==1 -> 0.
wrong = c[d==1]
print(one, wrong)

[10 30] 5


In [21]:
import numpy as np

# log of e, 2, and 10
print(np.log(np.e))
print(np.log2(2))
print(np.log10(10))

1.0
1.0
1.0


#### matplotlib

In [22]:
import matplotlib.pyplot as plt

plt.figure()

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>