#numpy, matplotlib and some useful packages

#### numpy array

In [10]:
import numpy as np

data = np.array([[1,2,3],[4,5,6]])
n,d = data.shape
print(data)
print(n,d)

[[1 2 3]
 [4 5 6]]
2 3


In [18]:
import numpy as np

zero_vector = np.zeros(5)
print(zero_vector)

# useful operation for numpy array
print(1-zero_vector)

# implement inner product
print(zero_vector.T) # T stands for transpose
print((1-zero_vector).T.dot(3-zero_vector))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
15.0


In [22]:
import numpy as np

# norm
vec =  1 - np.zeros(5)
# sum of every elements, norm 1
print(np.linalg.norm(vec , ord=1))
# Euclidean distance, norm 2
print(np.linalg.norm(vec , ord=2))

5.0
2.23606797749979


#### matplotlib

In [23]:
import matplotlib.pyplot as plt

plt.figure()

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

In [13]:
import numpy as np

print(np.exp(3))
print(np.exp(np.array([1,2,3],[4,5,6])))

20.085536923187668


TypeError: Field elements must be 2- or 3-tuples, got '4'